import os
import matplotlib as mpl

mpl.use("pgf")
mpl.rcParams["svg.fonttype"] = "none"
mpl.rcParams["font.family"] = "serif"
mpl.rcParams["figure.dpi"] = 96
mpl.rcParams["font.size"] = 12
mpl.rcParams["axes.labelsize"] = 12
mpl.rcParams["legend.fontsize"] = 10
mpl.rcParams["xtick.labelsize"] = 10
mpl.rcParams["ytick.labelsize"] = 10

mpl.rcParams.update(
    {
        "pgf.texsystem": "pdflatex",
        "pgf.rcfonts": False,
        "pgf.preamble": r"""
        \usepackage{acro}
        \usepackage{microtype}
        \usepackage{siunitx}
        \sisetup{per-mode = symbol}
        
        % Your specific scalebox formatting
        \acsetup{
            format/short = \scalebox{0.9}
        }
        
        % Only declare the acronyms and units you actually use in the plots
        \DeclareSIUnit{\iops}{IOPS}
        \DeclareAcronym{iops}{
          short = IOPS,
          long  = input/output operations per second,
        }
        
        % Your custom macros
        \newcommand{\hro}{\texttt{HIGH\_RECOVERY\_OPS} }
        \newcommand{\hco}{\texttt{HIGH\_CLIENT\_OPS} }
        \newcommand{\bal}{\texttt{BALANCED} }
    """,
    }
)
import matplotlib.pyplot as plt
import pandas as pd
import sys
import textwrap
import re


def fix_svg_latex_escapes(svg_path):
    """Post-process SVG to escape underscores in text tags for LaTeX inkscapelatex."""
    with open(svg_path, "r") as f:
        content = f.read()

    def repl(match):
        return match.group(0).replace("_", "\\_")

    new_content = re.sub(r"<text[^>]*>.*?</text>", repl, content, flags=re.DOTALL)
    with open(svg_path, "w") as f:
        f.write(new_content)


# Ensure tools is in path
try:
    from tools.sim_analysis import SimulationRun
except ImportError:
    sys.path.append(os.getcwd())
    from tools.sim_analysis import SimulationRun


ANNOTATE_GIT_HASH = False


def main():
    if "snakemake" in globals():
        client_metrics_files = snakemake.input.client_metrics
        mon_metrics_files = snakemake.input.mon_metrics
        net_metrics_files = snakemake.input.net_metrics
        output_dir = snakemake.params.output_dir
        git_hash = snakemake.params.get("git_hash", "unknown")
    else:
        # Fallback for manual testing (if set by wrapper) or sys.argv could be added here
        try:
            # Check if we have manually injected variables in the module scope (from wrapper)
            # This is a bit hacky but keeps the wrapper working if we update it
            client_metrics_files = globals().get("client_metrics_files")
            mon_metrics_files = globals().get("mon_metrics_files")
            net_metrics_files = globals().get("net_metrics_files")
            output_dir = globals().get("output_dir")
            git_hash = globals().get("git_hash", "unknown")

            if not (
                client_metrics_files
                and mon_metrics_files
                and net_metrics_files
                and output_dir
            ):
                raise ValueError("Missing inputs")

        except (NameError, ValueError):
            print(
                "This script is intended to be run via Snakemake or with proper globals injected."
            )
            sys.exit(1)

    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # Helper for git hash
    def add_git_hash(fig):
        if not ANNOTATE_GIT_HASH:
            return
        escaped_hash = git_hash
        fig.text(
            0.99,
            0.01,
            f"generated by git commit: {escaped_hash}",
            ha="right",
            va="bottom",
            fontsize=8,
            color="gray",
            alpha=0.5,
        )

    original_labels = []
    raw_labels = []
    run_objects = []

    # Zip together the file lists
    # We assume they are strictly ordered and correspond to each other
    for c_file, m_file, n_file in zip(
        client_metrics_files, mon_metrics_files, net_metrics_files
    ):
        # Use directory name as label, or part of it
        dirname = os.path.dirname(c_file)
        # simplistic label: last component of directory
        label = os.path.basename(dirname)
        if label == "vscode":  # fallback if run in vscode dev setup
            label = "current_run"

        # Try to find topology
        topo_file = os.path.join(dirname, "topology.json")

        run = SimulationRun(
            mon_path=m_file,
            net_path=n_file,
            client_path=c_file,
            topology_path=topo_file,
        )
        original_labels.append(label)
        raw_labels.append(label)
        run_objects.append(run)

    import re

    parsed_runs = []
    profiles = set()

    for orig_label, label, run in zip(original_labels, raw_labels, run_objects):
        sat_time = run.get_saturation_time(
            ["dc-0_uplink_DOWN", "dc-0_uplink_UP"], threshold=0.8
        )

        m = re.match(r"big_cluster_add_(\d+)_(.*)", orig_label)
        if m:
            n_val = int(m.group(1))
            prof = m.group(2)
            parsed_runs.append(
                {
                    "type": "grid",
                    "n": n_val,
                    "profile": prof,
                    "orig_label": orig_label,
                    "label": label,
                    "run": run,
                    "sat_time": sat_time,
                }
            )
            profiles.add(prof)
        else:
            parsed_runs.append(
                {
                    "type": "other",
                    "orig_label": orig_label,
                    "label": label,
                    "run": run,
                    "sat_time": sat_time,
                }
            )

    # New Grid Visualization
    grid_runs = [r for r in parsed_runs if r["type"] == "grid"]
    other_runs = [r for r in parsed_runs if r["type"] == "other"]

    if grid_runs or other_runs:
        fig, axes = plt.subplots(
            1, 2, figsize=(5.59, 3.0), gridspec_kw={"width_ratios": [3, 1]}, sharey=True
        )
        ax_grid, ax_others = axes

        if grid_runs:
            df_grid = pd.DataFrame(grid_runs)
            pivot = df_grid.pivot(index="n", columns="profile", values="sat_time")
            pivot.columns = [
                rf"\texttt{{{c.replace('_', r'\_')}}}" for c in pivot.columns
            ]
            pivot.plot(kind="line", marker="o", ax=ax_grid)
            ax_grid.set_xlabel("Batch Size ($N$)")
            ax_grid.set_ylabel("Saturation Time (s)")
            ax_grid.grid(True)

        if other_runs:
            df_others = pd.DataFrame(other_runs)
            # Remove prefix for display, split at _ to newlines, and format as texttt
            df_others["display_label"] = (
                df_others["orig_label"]
                .str.replace("big_cluster_", "", regex=False)
                .apply(
                    lambda x: "\n".join(
                        [rf"\texttt{{{part}}}" for part in x.split("_")]
                    )
                )
            )
            df_others.plot(
                kind="bar",
                x="display_label",
                y="sat_time",
                ax=ax_others,
                color="gray",
                legend=False,
            )
            ax_others.set_xlabel("Cases")
            ax_others.grid(True, axis="y")
            ax_others.tick_params(axis="y", left=False, labelleft=False)
            ax_others.tick_params(axis="x", rotation=0)

        plt.tight_layout(rect=[0, 0, 1, 0.95])
        add_git_hash(fig)
        out_path = os.path.join(output_dir, "link_saturation.svg")
        plt.savefig(out_path)
        plt.savefig(out_path.replace(".svg", ".pgf"))
        print(f"Saved link saturation visualization to {out_path}")
        plt.close()

    # Filter for standard plots
    selected_runs = []
    if profiles:
        for prof in profiles:
            prof_runs = [
                r for r in parsed_runs if r["type"] == "grid" and r["profile"] == prof
            ]
            prof_runs.sort(key=lambda x: x["n"])
            valid_runs = [r for r in prof_runs if r["sat_time"] <= 0]
            if valid_runs:
                selected_runs.append(valid_runs[-1])
            elif prof_runs:
                selected_runs.append(prof_runs[0])

        for r in parsed_runs:
            if r["type"] == "other":
                selected_runs.append(r)

        selected_runs.sort(key=lambda x: x["orig_label"])
        raw_labels = [r["label"] for r in selected_runs]
        run_objects = [r["run"] for r in selected_runs]

    # Shorten labels by removing common prefix
    if raw_labels:
        # Pass 1: Global common prefix
        prefix = os.path.commonprefix(raw_labels)
        if len(prefix) > 4:
            raw_labels = [l[len(prefix) :].lstrip(" _-") for l in raw_labels]

        # Pass 2: Common prefix of non-empty labels (e.g. 'clients_')
        non_empty = [l for l in raw_labels if l]
        if non_empty:
            prefix2 = os.path.commonprefix(non_empty)
            # Only strip if it covers a significant portion or is a specific marker
            if len(prefix2) > 2:
                raw_labels = [
                    l[len(prefix2) :].lstrip(" _-") if l else l for l in raw_labels
                ]

        # Finalize
        final_labels = []
        for l in raw_labels:
            if not l:
                l = "baseline"
            final_labels.append(l)
        raw_labels = final_labels

    # Combine with runs and wrap text
    runs = []
    for label, run in zip(raw_labels, run_objects):
        if isinstance(label, str):
            # For X-ticks to wrap properly, we replace underscores with a newline
            wrapped_label = label.replace("_", "\n")
            # Escape underscores for pgf/latex rendering
            label = label.replace("_", r"\_")
        else:
            wrapped_label = label

        runs.append({"label": label, "wrapped_label": wrapped_label, "run": run})

    # Plot 1: Compare Client Throughput (Read and Write)
    for metric in ["read", "write"]:
        fig, ax = plt.subplots(1, 1, figsize=(5.59, 3.5))
        has_data = False

        for r_obj in runs:
            label = r_obj["label"]
            run = r_obj["run"]
            tp = run.get_client_throughput(window_size=10)
            if tp.empty or metric not in tp.columns or not (tp[metric] > 0).any():
                continue

            has_data = True
            start_time, end_time = run.get_recovery_times()

            (line,) = ax.plot(tp.index, tp[metric].values, label=label, linewidth=1.5)
            color = line.get_color()

            if start_time is not None:
                ax.axvline(x=start_time, color=color, linestyle=":", alpha=0.8)
            if end_time is not None:
                ax.axvline(x=end_time, color=color, linestyle="--", alpha=0.8)

        ax.set_xlabel("Time (s)")
        if has_data:
            ax.set_ylabel(f"{metric.capitalize()} Throughput (MiB/s)")
            if metric == "read":
                ax.set_ylim(bottom=0)
            ax.legend(
                loc="upper center", bbox_to_anchor=(0.5, -0.15), ncol=2, frameon=False
            )
        else:
            ax.set_ylabel(f"{metric.capitalize()} Throughput (MiB/s)")
            ax.set_title(f"Client {metric.capitalize()} Throughput (No Data)")

        ax.grid(True)
        plt.tight_layout()
        add_git_hash(fig)

        output_path = os.path.join(output_dir, f"client_{metric}_throughput.svg")
        plt.savefig(output_path)
        plt.savefig(output_path.replace(".svg", ".pgf"))
        fix_svg_latex_escapes(output_path)
        print(f"Saved comparison to {output_path}")
        plt.close()

    # Plot 1b: Compare Client Throughput for all 'n' of each profile
    for prof in profiles:
        prof_grid_runs = [
            r for r in parsed_runs if r["type"] == "grid" and r["profile"] == prof
        ]
        if prof_grid_runs:
            prof_grid_runs.sort(key=lambda x: x["n"])

            has_read = False
            has_write = False
            for metric in ["read", "write"]:
                fig, ax = plt.subplots(1, 1, figsize=(5.59, 3.5))
                has_data = False

                for r in prof_grid_runs:
                    label = str(r["n"])
                    run = r["run"]
                    tp = run.get_client_throughput(window_size=10)
                    if (
                        tp.empty
                        or metric not in tp.columns
                        or not (tp[metric] > 0).any()
                    ):
                        continue

                    has_data = True
                    start_time, end_time = run.get_recovery_times()

                    (line,) = ax.plot(
                        tp.index, tp[metric].values, label=label, linewidth=1.5
                    )
                    color = line.get_color()

                    if start_time is not None:
                        ax.axvline(x=start_time, color=color, linestyle=":", alpha=0.3)
                    if end_time is not None:
                        ax.axvline(x=end_time, color=color, linestyle="--", alpha=0.3)

                ax.set_xlabel("Time (s)")
                if has_data:
                    ax.set_ylabel(f"{metric.capitalize()} Throughput (MiB/s)")
                    display_prof = prof.replace("_", r"\_")
                    if metric == "read":
                        ax.set_ylim(bottom=0)
                    ax.legend(
                        title="Batch Size ($N$)",
                        loc="lower right",
                        ncol=1,
                        fontsize="small",
                        frameon=False,
                    )
                else:
                    display_prof = prof.replace("_", r"\_")
                    ax.set_ylabel(f"{metric.capitalize()} Throughput (MiB/s)")
                    ax.set_title(
                        rf"Client {metric.capitalize()} Throughput (\texttt{{{display_prof}}}) (No Data)"
                    )

                ax.grid(True)
                plt.tight_layout()
                add_git_hash(fig)

                output_path_prof = os.path.join(
                    output_dir, f"client_{metric}_throughput_{prof}_all_n.svg"
                )
                plt.savefig(output_path_prof)
                plt.savefig(output_path_prof.replace(".svg", ".pgf"))
                fix_svg_latex_escapes(output_path_prof)
                print(
                    f"Saved {prof} profile throughput comparison to {output_path_prof}"
                )
                plt.close()

    # Plot 2: Recovery Detailed Progress
    fig, (ax1, ax2) = plt.subplots(
        nrows=2,
        ncols=1,
        figsize=(5.59, 4.5),
        sharex=True,
        gridspec_kw={"height_ratios": [3, 1]},
    )

    # Calculate global recovery window
    global_start = float("inf")
    global_end = float("-inf")
    has_recovery_data = False

    # Helper to collect data first so we can calculate offsets
    recovery_series = []
    max_concurrency = 0

    for r_obj in runs:
        label = r_obj["label"]
        run = r_obj["run"]
        start_time, end_time = run.get_recovery_times()
        if start_time is None:
            continue

        has_recovery_data = True
        global_start = min(global_start, start_time)
        if end_time is not None:
            global_end = max(global_end, end_time)

        # Prepare Data
        mon_df = run.mon_df
        # Filter for relevant range
        df_rec = mon_df[mon_df["time"] >= start_time].copy()

        if df_rec.empty:
            continue

        # Calculate Backlog
        df_rec["backlog"] = df_rec["backfill"] + df_rec["backfill_wait"]

        # Track max concurrency for offset calculation
        if not df_rec["backfill"].empty:
            max_concurrency = max(max_concurrency, df_rec["backfill"].max())

        recovery_series.append({"label": label, "df": df_rec})

    if has_recovery_data:
        # Determine offset for seismic plot
        # Add a bit of padding, e.g., 20% or at least 1
        offset_step = max(1, max_concurrency * 1.2)

        for i, series in enumerate(recovery_series):
            label = series["label"]
            df_rec = series["df"]

            # Plot Backlog on Top Axis (ax1)
            (l1,) = ax1.plot(
                df_rec["time"], df_rec["backlog"], label=label, linewidth=1.5
            )
            color = l1.get_color()

            # Plot Active Backfill on Bottom Axis (ax2)
            # Offset = i * offset_step
            base_y = i * offset_step
            # We want the baseline to be at base_y, and values adding to it
            # But "seismic" usually means centered or just displaced.
            # The user asked for "starting from different height".
            # Let's plot (y + base_y)

            y_values = df_rec["backfill"] + base_y

            # Add a baseline for reference? Or just the trace?
            # User said "discrete behavior... quantized to integers".
            # Step plot is good.
            ax2.plot(
                df_rec["time"],
                y_values,
                label=label,
                color=color,
                linestyle="-",
                drawstyle="steps-post",
                linewidth=1.5,
            )

            # Maybe add a faint zero line for this series?
            ax2.axhline(y=base_y, color=color, linestyle=":", alpha=0.3, linewidth=0.5)

        # Set X-Axis Limits
        margin = (global_end - global_start) * 0.05
        ax1.set_xlim(global_start - margin, global_end + margin)
        # ax2 shares x, so it will update automatically

        ax1.set_ylabel("Total Backlog (PGs)")
        ax1.set_title("Recovery Progress")
        ax1.grid(True)
        ax1.legend(loc="upper right")

        ax2.set_xlabel("Time (s)")
        # ax2.set_ylabel("#Active")
        ax2.set_title("Active Backfills")
        # Remove Y ticks on the second plot as they are arbitrary due to offset
        ax2.set_yticks([])

        # Maybe add text labels for each series on the left or right of the plot?
        for i, series in enumerate(recovery_series):
            label = series["label"]
            y_pos = i * offset_step + (
                offset_step / 2
            )  # approximate center of the band
            # Or just at the base?
            y_pos = i * offset_step
            # Place label at the start time?
            # Let's just rely on the legend for color matching,
            # OR put text at the far right.
            ax2.text(
                global_end + margin,
                y_pos,
                label,
                va="bottom",
                ha="right",
                color="black",
                alpha=0.7,
            )

        add_git_hash(fig)

        output_path_rec = os.path.join(output_dir, "recovery_progress.svg")
        plt.savefig(output_path_rec)
        plt.savefig(output_path_rec.replace(".svg", ".pgf"))
        fix_svg_latex_escapes(output_path_rec)
        print(f"Saved recovery visualization to {output_path_rec}")
    else:
        print("No recovery data found, skipping recovery plot.")

    plt.close()

    # Plot 3: Latency Comparison
    latency_data = []
    labels = []

    for r_obj in runs:
        label = r_obj["label"]
        wrapped_label = r_obj["wrapped_label"]
        run = r_obj["run"]
        stats = run.get_latency_stats()
        if not stats:
            continue

        # Flatten nested stats
        flat_stats = {}
        for op_type, type_stats in stats.items():
            if isinstance(type_stats, dict):
                for metric, val in type_stats.items():
                    key = f"{metric} ({op_type})" if op_type != "all" else metric
                    flat_stats[key] = val
            else:
                flat_stats[op_type] = type_stats

        # Skip cases with no actual client traffic (all values zero)
        values = [v for k, v in flat_stats.items() if k != "label"]
        if not values or all(v == 0 for v in values):
            continue

        flat_stats["label"] = wrapped_label
        latency_data.append(flat_stats)
        labels.append(wrapped_label)

    df_lat = pd.DataFrame(latency_data) if latency_data else pd.DataFrame()
    if not df_lat.empty:
        df_lat = df_lat.set_index("label")

        # Reorder columns for logical progression
        cols = [
            "avg (read)",
            "avg (write)",
            "p95 (read)",
            "p95 (write)",
            "p99 (read)",
            "p99 (write)",
            "p99.5 (read)",
            "p99.5 (write)",
            "avg",
            "p95",
            "p99",
            "p99.5",
        ]
        # Filter strictly those we put in
        cols = [c for c in cols if c in df_lat.columns]
        df_lat = df_lat[cols]

    # Determine if we should display in milliseconds based on max value
    max_latency = df_lat.max().max() if not df_lat.empty else 0
    use_ms = max_latency < 1.0  # Use ms if all values are under 1 second

    if use_ms:
        # Convert to milliseconds for display
        if not df_lat.empty:
            df_lat = df_lat * 1000
        latency_unit = "ms"
    else:
        latency_unit = "s"

    def format_latency(val):
        """Format latency value with appropriate precision."""
        if val >= 100:
            return f"{val:.0f}"
        elif val >= 10:
            return f"{val:.1f}"
        elif val >= 1:
            return f"{val:.2f}"
        else:
            return f"{val:.3f}"

    # Split into Read and Write dataframes if columns exist
    read_cols = [c for c in df_lat.columns if "(read)" in c] if not df_lat.empty else []
    write_cols = (
        [c for c in df_lat.columns if "(write)" in c] if not df_lat.empty else []
    )

    for metric_type, metric_cols in [("read", read_cols), ("write", write_cols)]:
        fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(5.59, 3.5))

        if (
            metric_cols
            and not df_lat[metric_cols].empty
            and (df_lat[metric_cols] > 0).any().any()
        ):
            df_metric = df_lat[metric_cols].copy()
            df_metric.columns = [
                c.replace(f" ({metric_type})", "") for c in df_metric.columns
            ]
            df_metric.plot(kind="bar", ax=ax, rot=0)
            df_metric.to_csv(
                os.path.join(output_dir, f"{metric_type}_latency_comparison.csv")
            )

            ax.set_ylabel(f"Latency ({latency_unit})")
            ax.grid(True, axis="y")
            ax.legend(title="Metric", loc="upper left", bbox_to_anchor=(1, 1))
        else:
            ax.set_ylabel(f"Latency ({latency_unit})")
            ax.set_title(f"{metric_type.capitalize()} Latency (No Data)")

        ax.set_xlabel("Cases")
        ax.tick_params(axis="x", rotation=0)

        plt.tight_layout()
        add_git_hash(fig)

        output_path_lat = os.path.join(
            output_dir, f"{metric_type}_latency_comparison.svg"
        )
        plt.savefig(output_path_lat)
        plt.savefig(output_path_lat.replace(".svg", ".pgf"))
        fix_svg_latex_escapes(output_path_lat)
        print(f"Saved latency visualization to {output_path_lat}")
        plt.close()

    # Plot 3b: Latency Comparison for all 'n' of each profile
    for prof in profiles:
        prof_grid_runs = [
            r for r in parsed_runs if r["type"] == "grid" and r["profile"] == prof
        ]
        if not prof_grid_runs:
            continue

        prof_grid_runs.sort(key=lambda x: x["n"])
        lat_data_prof = []
        for r in prof_grid_runs:
            run = r["run"]
            stats = run.get_latency_stats()
            if not stats:
                continue

            flat_stats = {}
            for op_type, type_stats in stats.items():
                if isinstance(type_stats, dict):
                    for metric, val in type_stats.items():
                        key = f"{metric} ({op_type})" if op_type != "all" else metric
                        flat_stats[key] = val
                else:
                    flat_stats[op_type] = type_stats

            values = [v for k, v in flat_stats.items()]
            if not values or all(v == 0 for v in values):
                continue

            flat_stats["label"] = str(r["n"])
            lat_data_prof.append(flat_stats)

        df_lat = pd.DataFrame(lat_data_prof) if lat_data_prof else pd.DataFrame()
        if not df_lat.empty:
            df_lat = df_lat.set_index("label")

            cols = [
                "avg (read)",
                "avg (write)",
                "p95 (read)",
                "p95 (write)",
                "p99 (read)",
                "p99 (write)",
                "p99.5 (read)",
                "p99.5 (write)",
                "avg",
                "p95",
                "p99",
                "p99.5",
            ]
            cols = [c for c in cols if c in df_lat.columns]
            df_lat = df_lat[cols]

            # Drop purely 0-value columns just in case
            df_lat = df_lat.loc[:, (df_lat != 0).any(axis=0)]

        max_latency = df_lat.max().max() if not df_lat.empty else 0
        use_ms = max_latency < 1.0

        if use_ms:
            if not df_lat.empty:
                df_lat = df_lat * 1000
            latency_unit = "ms"
        else:
            latency_unit = "s"

        def format_lat(val):
            if val >= 100:
                return f"{val:.0f}"
            elif val >= 10:
                return f"{val:.1f}"
            elif val >= 1:
                return f"{val:.2f}"
            else:
                return f"{val:.3f}"

        read_cols = (
            [c for c in df_lat.columns if "(read)" in c] if not df_lat.empty else []
        )
        write_cols = (
            [c for c in df_lat.columns if "(write)" in c] if not df_lat.empty else []
        )

        for metric_type, metric_cols in [("read", read_cols), ("write", write_cols)]:
            # xticks are smaller than in many other plots so it look bigger, height 3 to compensate
            fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(5.59, 3))

            if (
                metric_cols
                and not df_lat[metric_cols].empty
                and (df_lat[metric_cols] > 0).any().any()
            ):
                df_metric = df_lat[metric_cols].copy()
                df_metric.columns = [
                    c.replace(f" ({metric_type})", "") for c in df_metric.columns
                ]
                df_metric.plot(
                    kind="bar", ax=ax, rot=0, width=0.8, edgecolor="white", linewidth=1
                )
                df_metric.to_csv(
                    os.path.join(
                        output_dir, f"{metric_type}_latency_comparison_{prof}_all_n.csv"
                    )
                )

                ax.set_ylabel(f"Latency ({latency_unit})")
                display_prof = prof.replace("_", r"\_")
                ax.grid(True, axis="y")
                ax.legend(title="Metric")
            else:
                ax.set_ylabel(f"Latency ({latency_unit})")
                display_prof = prof.replace("_", r"\_")
                ax.set_title(
                    rf"Client {metric_type.capitalize()} Latency (\texttt{{{display_prof}}}) (No Data)"
                )

            ax.set_xlabel("Batch Size ($N$)")
            ax.tick_params(axis="x", rotation=0)

            plt.tight_layout()
            add_git_hash(fig)

            output_path_lat_prof = os.path.join(
                output_dir, f"{metric_type}_latency_comparison_{prof}_all_n.svg"
            )
            plt.savefig(output_path_lat_prof)
            plt.savefig(output_path_lat_prof.replace(".svg", ".pgf"))
            fix_svg_latex_escapes(output_path_lat_prof)
            print(
                f"Saved {prof} profile latency visualization to {output_path_lat_prof}"
            )
            plt.close()

    # Plot 4: IOPS Comparison
    iops_data = []
    iops_labels = []

    for r_obj in runs:
        label = r_obj["label"]
        wrapped_label = r_obj["wrapped_label"]
        run = r_obj["run"]
        stats = run.get_iops_stats()
        if not stats:
            continue

        stats["label"] = wrapped_label
        iops_data.append(stats)
        iops_labels.append(wrapped_label)

    df_iops = pd.DataFrame(iops_data) if iops_data else pd.DataFrame()
    if not df_iops.empty:
        df_iops = df_iops.set_index("label")

    for metric in ["read", "write"]:
        fig = plt.figure(figsize=(5.59, 3.5))
        ax = plt.gca()
        has_data = (
            not df_iops.empty
            and metric in df_iops.columns
            and (df_iops[metric] > 0).any()
        )

        if has_data:
            df_metric = df_iops[[metric]]
            df_metric.plot(kind="bar", ax=ax, rot=0, legend=False)

            max_iops = df_metric.values.max()
            ax.set_ylim(0, max_iops * 1.15)

            for p in ax.patches:
                height = p.get_height()
                if height > 0:
                    ax.annotate(
                        f"{height:.0f}",
                        (p.get_x() + p.get_width() / 2.0, height),
                        ha="center",
                        va="bottom",
                        xytext=(0, 2),
                        textcoords="offset points",
                    )
        else:
            plt.title(f"Client {metric.capitalize()} IOPS Comparison (No Data)")

        plt.xlabel("Cases")
        plt.ylabel("IOPS")
        plt.grid(True, axis="y")

        # Horizontal x labels
        plt.xticks(rotation=0, ha="center")

        plt.tight_layout()
        add_git_hash(fig)

        output_path_iops = os.path.join(output_dir, f"{metric}_iops_comparison.svg")
        plt.savefig(output_path_iops)
        plt.savefig(output_path_iops.replace(".svg", ".pgf"))
        fix_svg_latex_escapes(output_path_iops)
        print(f"Saved IOPS visualization to {output_path_iops}")
        plt.close()

    # Plot 4b: IOPS Comparison for all 'n' of each profile
    for prof in profiles:
        prof_grid_runs = [
            r for r in parsed_runs if r["type"] == "grid" and r["profile"] == prof
        ]
        if not prof_grid_runs:
            continue

        prof_grid_runs.sort(key=lambda x: x["n"])
        iops_data_prof = []
        for r in prof_grid_runs:
            run = r["run"]
            stats = run.get_iops_stats()
            if not stats:
                continue
            stats["label"] = str(r["n"])
            iops_data_prof.append(stats)

        df_iops = pd.DataFrame(iops_data_prof) if iops_data_prof else pd.DataFrame()
        if not df_iops.empty:
            df_iops = df_iops.set_index("label")

        for metric in ["read", "write"]:
            fig = plt.figure(figsize=(5.59, 3.5))
            ax = plt.gca()
            has_data = (
                not df_iops.empty
                and metric in df_iops.columns
                and (df_iops[metric] > 0).any()
            )

            if has_data:
                df_metric = df_iops[[metric]]
                df_metric.plot(kind="bar", ax=ax, rot=0, legend=False)

                max_iops = df_metric.values.max()
                ax.set_ylim(0, max_iops * 1.15)

                for p in ax.patches:
                    height = p.get_height()
                    if height > 0:
                        ax.annotate(
                            f"{height:.0f}",
                            (p.get_x() + p.get_width() / 2.0, height),
                            ha="center",
                            va="bottom",
                            xytext=(0, 2),
                            textcoords="offset points",
                        )
                display_prof = prof.replace("_", r"\_")
                plt.title(
                    rf"Client {metric.capitalize()} IOPS Comparison (\texttt{{{display_prof}}})"
                )
            else:
                display_prof = prof.replace("_", r"\_")
                plt.title(
                    rf"Client {metric.capitalize()} IOPS Comparison (\texttt{{{display_prof}}}) (No Data)"
                )

            plt.xlabel("Batch Size ($N$)")
            plt.ylabel("IOPS")
            plt.grid(True, axis="y")
            plt.xticks(rotation=0, ha="center")
            plt.tight_layout()
            add_git_hash(fig)

            output_path_iops_prof = os.path.join(
                output_dir, f"{metric}_iops_comparison_{prof}_all_n.svg"
            )
            plt.savefig(output_path_iops_prof)
            plt.savefig(output_path_iops_prof.replace(".svg", ".pgf"))
            fix_svg_latex_escapes(output_path_iops_prof)
            print(f"Saved {prof} profile IOPS visualization to {output_path_iops_prof}")
            plt.close()


if __name__ == "__main__":
    main()
