import os
import matplotlib as mpl

mpl.use("pgf")
mpl.rcParams["svg.fonttype"] = "none"
mpl.rcParams["font.family"] = "serif"
mpl.rcParams["figure.dpi"] = 96
mpl.rcParams["font.size"] = 12
mpl.rcParams["axes.labelsize"] = 12
mpl.rcParams["legend.fontsize"] = 10
mpl.rcParams["xtick.labelsize"] = 10
mpl.rcParams["ytick.labelsize"] = 10

mpl.rcParams.update(
    {
        "pgf.texsystem": "pdflatex",
        "pgf.rcfonts": False,
        "pgf.preamble": r"""
        \usepackage{acro}
        \usepackage{microtype}
        \usepackage{siunitx}
        \sisetup{per-mode = symbol}
        
        % Your specific scalebox formatting
        \acsetup{
            format/short = \scalebox{0.9}
        }
        
        % Only declare the acronyms and units you actually use in the plots
        \DeclareSIUnit{\iops}{IOPS}
        \DeclareAcronym{iops}{
          short = IOPS,
          long  = input/output operations per second,
        }
        
        % Your custom macros
        \newcommand{\hro}{\texttt{HIGH\_RECOVERY\_OPS} }
        \newcommand{\hco}{\texttt{HIGH\_CLIENT\_OPS} }
        \newcommand{\bal}{\texttt{BALANCED} }
    """,
    }
)
import matplotlib.pyplot as plt
import pandas as pd
import json

try:
    from tools.sim_analysis import SimulationRun
except ImportError:
    # Handle case where tools is not in pythonpath (e.g. running from root)
    import sys

    sys.path.append(os.getcwd())
    from tools.sim_analysis import SimulationRun


ANNOTATE_GIT_HASH = False

if "snakemake" not in globals():
    mon_metrics_file = "results/vscode/mon_metrics.csv"
    net_metrics_file = "results/vscode/net_metrics.csv"
    client_metrics_file = "results/vscode/client_metrics.csv"
    output_dir = "results/vscode/figures"
    git_hash = "unknown"
    case_name = "vscode"
else:
    mon_metrics_file = snakemake.input.mon_metrics
    net_metrics_file = snakemake.input.net_metrics
    client_metrics_file = snakemake.input.client_metrics
    output_dir = snakemake.params.output_dir
    git_hash = snakemake.params.get("git_hash", "unknown")
    case_name = snakemake.params.get("case_name", "unknown")

display_case_name = case_name.replace("_", r"\_")


import re


def fix_svg_latex_escapes(svg_path):
    """Post-process SVG to escape underscores in text tags for LaTeX inkscapelatex."""
    with open(svg_path, "r") as f:
        content = f.read()

    def repl(match):
        return match.group(0).replace("_", "\\_")

    new_content = re.sub(r"<text[^>]*>.*?</text>", repl, content, flags=re.DOTALL)
    with open(svg_path, "w") as f:
        f.write(new_content)


def add_git_hash(fig):
    if not ANNOTATE_GIT_HASH:
        return
    fig.text(
        0.99,
        0.01,
        f"generated by git commit: {git_hash}",
        ha="right",
        va="bottom",
        color="gray",
        alpha=0.5,
    )


def viz_mon_metrics(sim_run):
    mon_metrics_df = sim_run.mon_df
    if mon_metrics_df is None:
        return

    fig = plt.figure(figsize=(5.59, 3.5))

    # Plot all columns except 'time'
    for column in mon_metrics_df.columns:
        if column == "time":
            continue
        plt.plot(
            mon_metrics_df["time"],
            mon_metrics_df[column],
            label=column if isinstance(column, str) else column,
            marker="o",
            linestyle="-",
            markersize=2,
        )

    plt.xlabel("Time (s)")
    plt.ylabel("Number of PGs")
    plt.ylabel("Number of PGs")
    plt.title(rf"PG States Over Time (\texttt{{{display_case_name}}})")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    add_git_hash(fig)

    output_path = os.path.join(output_dir, "pgmap_plot.svg")
    plt.savefig(output_path)
    plt.savefig(output_path.replace(".svg", ".pgf"))
    fix_svg_latex_escapes(output_path)
    print(f"Saved plot to {output_path}")
    plt.close()


def viz_client_metrics(sim_run):
    throughput = sim_run.get_client_throughput()
    window_size = 10

    for metric in ["read", "write"]:
        fig = plt.figure(figsize=(5.59, 3.5))

        has_data = (
            not throughput.empty
            and metric in throughput.columns
            and (throughput[metric] > 0).any()
        )

        if has_data:
            plot_index = throughput.index
            plt.plot(
                plot_index,
                throughput[metric],
                label=f"{metric.capitalize()} ({window_size}s avg)",
                linestyle="-",
                linewidth=1.5,
            )
            plt.title(
                rf"Client {metric.capitalize()} Throughput Over Time (Smoothed {window_size}s) - \texttt{{{display_case_name}}}"
            )
            if metric == "read":
                plt.ylim(bottom=0)
            plt.legend(
                loc="upper center", bbox_to_anchor=(0.5, -0.15), ncol=2, frameon=False
            )
        else:
            plt.title(
                rf"Client {metric.capitalize()} Throughput (No Data) - \texttt{{{display_case_name}}}"
            )

        plt.xlabel("Time (s)")
        plt.ylabel("Throughput (MiB/s)")
        plt.grid(True)
        plt.tight_layout()
        add_git_hash(fig)

        output_path = os.path.join(output_dir, f"client_{metric}_throughput.svg")
        plt.savefig(output_path)
        plt.savefig(output_path.replace(".svg", ".pgf"))
        fix_svg_latex_escapes(output_path)
        print(f"Saved plot to {output_path}")
        plt.close()


def viz_net_metrics(sim_run):
    net_df = sim_run.net_df
    if net_df is None or net_df.empty:
        print("Net metrics empty, skipping viz_net_metrics")
        return

    topology = sim_run.topology
    if not topology:
        print(f"Topology not loaded")
        return

    # 1. Parse Topology and calculate Tree Layout
    # Simple recursive layout:
    # x: centered above children
    # y: based on depth

    node_pos = {}  # id -> (x, y)
    node_names = {}  # id -> name
    leaf_nodes = set()  # ids of leaf nodes (hosts)
    edges = []  # (parent_id, child_id, uplink_name, bandwidth)

    def format_bw(bps):
        if bps >= 1e9:
            return f"{bps / 1e9:.0f}G"
        elif bps >= 1e6:
            return f"{bps / 1e6:.0f}M"
        elif bps >= 1e3:
            return f"{bps / 1e3:.0f}K"
        return f"{bps:.0f}"

    def parse_and_layout(node, depth, x_start):
        """
        Returns (width, x_center) of the subtree
        """
        raw_children = node.get("children", [])
        node_id = node["id"]

        # Separate children: actors vs structural
        structural_children = []
        actor_children = []
        for child in raw_children:
            if child.get("type") == "actor":
                actor_children.append(child)
            else:
                structural_children.append(child)

        # Construct Label
        name_str = node.get("name", node_id)
        if name_str == "client_rack":
            name_str = "client"

        if actor_children:
            # Sort for consistency
            actor_names = []
            for c in actor_children:
                raw_name = c.get("name", c["id"])
                # Remove ", disk..." if present
                if "," in raw_name:
                    clean_name = raw_name.split(",")[0].strip()
                else:
                    clean_name = raw_name

                if clean_name.startswith("osd."):
                    clean_name = clean_name[4:]

                actor_names.append(clean_name)

            # Disable OSD IDs for thesis figure
            # formatted_actors = [f"({n})" for n in actor_names]
            # name_str += "\n" + "\n".join(formatted_actors)

        if node_id != "_world_":
            node_names[node_id] = name_str

        if not structural_children:
            # Leaf (topology-wise)
            leaf_nodes.add(node_id)
            width = 1.0
            x_center = x_start + 0.5
            if node_id != "_world_":
                node_pos[node_id] = (x_center, -float(depth))
            return width, x_center

        # Internal node
        current_x = x_start
        child_xs = []

        for child in structural_children:
            w, cx = parse_and_layout(child, depth + 1, current_x)
            current_x += w
            child_xs.append(cx)

            # Store edge info
            uplink = child.get("uplink")
            bw = child.get("bandwidth", 0)
            if uplink:
                edges.append((node_id, child["id"], uplink, bw))

        width = current_x - x_start
        x_center = sum(child_xs) / len(child_xs)
        if node_id != "_world_":
            node_pos[node_id] = (x_center, -float(depth))

        return width, x_center

    parse_and_layout(topology, 0, 0)

    # 2. Process Metrics
    # Calculate average utilization for each link
    avg_usage = sim_run.get_average_link_utilization()

    # Calculate x_span for width scaling
    xs = [pos[0] for pos in node_pos.values()]
    x_span = max(xs) - min(xs) if xs else 14

    # 3. Plot
    fig_width = max(14, x_span * 0.8)
    fig = plt.figure(figsize=(5.59, 4), dpi=96)
    ax = plt.gca()

    # Draw Edges
    for u, v, name, bw in edges:
        if u not in node_pos or v not in node_pos:
            continue

        ux, uy = node_pos[u]
        vx, vy = node_pos[v]

        # Determine Usage
        up_bps = avg_usage.get(f"{name}_UP", 0.0)
        down_bps = avg_usage.get(f"{name}_DOWN", 0.0)

        # Fallback if specific UP/DOWN not found but base name exists
        if up_bps == 0 and down_bps == 0 and name in avg_usage:
            up_bps = avg_usage[name]

        # metric is in bytes/s, bandwidth is in bits/s
        # Convert average usage to bits/s
        up_bps *= 8.0
        down_bps *= 8.0

        up_pct = (up_bps / bw * 100.0) if bw > 0 else 0.0
        down_pct = (down_bps / bw * 100.0) if bw > 0 else 0.0
        util_pct = max(up_pct, down_pct)

        bw_str = format_bw(bw)
        label_text = f"{bw_str}\nU: {up_pct:02.0f}%\nD: {down_pct:02.0f}%"
        # Style
        color = "#aaaaaa"  # default gray
        width = 1.0
        font_weight = "normal"

        if util_pct > 80:
            color = "#d62728"  # red
            width = 2.5
            font_weight = "bold"
        elif util_pct > 50:
            color = "#ff7f0e"  # orange
            width = 2.0
            font_weight = "bold"
        elif util_pct > 10:
            color = "#1f77b4"  # blue
            width = 1.5

        plt.plot([ux, vx], [uy, vy], color=color, linewidth=width, zorder=1)

        # Label with utilization (closer to destination node v)
        # label_x = ux + 0.7 * (vx - ux)
        # label_y = uy + 0.7 * (vy - uy)

        # plt.text(
        #     label_x,
        #     label_y,
        #     label_text,
        #     color="black",
        #     fontsize=7,
        #     ha="center",
        #     va="center",
        #     bbox=dict(facecolor="white", edgecolor="none", alpha=0.8, pad=1),
        # )

    # Draw Nodes
    for nid, (x, y) in node_pos.items():
        plt.scatter(x, y, s=150, c="lightgray", zorder=2, edgecolors="gray")
        # Offset label to avoid overlap with dot
        label = node_names.get(nid, nid)

        if nid in leaf_nodes:
            # Place label BELOW the node
            if len(leaf_nodes) <= 10:
                plt.text(
                    x,
                    y - 0.15,
                    label,
                    ha="center",
                    va="top",
                    fontweight="normal",
                )
        else:
            # Place label ABOVE the node (default)
            # Use extra offset for client to avoid overlap with siblings
            offset = 0.3 if label == "client" else 0.15
            plt.text(
                x,
                y + offset,
                label,
                ha="center",
                va="bottom",
                fontweight="normal",
            )

    # Calculate bounds for better centering and margins
    xs = [pos[0] for pos in node_pos.values()]
    ys = [pos[1] for pos in node_pos.values()]

    if xs and ys:
        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)

        x_span = max_x - min_x
        y_span = max_y - min_y

        # Add padding
        x_pad = max(0.2, x_span * 0.05)
        y_pad = max(0.2, y_span * 0.1)

        # Extra top padding for title/root label to avoid overlap
        top_pad = y_pad + 0.2

        ax.set_xlim(min_x - x_pad, max_x + x_pad)
        ax.set_ylim(min_y - y_pad, max_y + top_pad)

        max_lines = max(
            (node_names.get(nid, nid).count("\n") + 1 for nid in leaf_nodes), default=1
        )
        # Place it aligned with the rightmost node spread, below the lowest text
        if ANNOTATE_GIT_HASH:
            escaped_hash = git_hash
            plt.annotate(
                f"generated by git commit: {escaped_hash}",
                xy=(max_x, min_y - 0.15),
                xycoords="data",
                xytext=(0, -max_lines * 11 - 15),
                textcoords="offset points",
                ha="right",
                va="top",
                color="gray",
                alpha=0.5,
            )

    plt.axis("off")

    # Save
    output_path = os.path.join(output_dir, "network_topology.svg")
    plt.savefig(output_path, bbox_inches="tight")
    plt.savefig(output_path.replace(".svg", ".pgf"), bbox_inches="tight")
    fix_svg_latex_escapes(output_path)
    print(f"Saved plot to {output_path}")
    plt.close()


def viz_star_link_utilization(sim_run):
    links = sim_run.get_star_links()
    if not links:
        print("No star links found or topology missing")
        return

    # If exactly two data centers (links) are connected, only draw the first one.
    if len(links) == 2:
        print("Exactly 2 star links found, visualizing only the first one.")
        links = links[:1]

    # Get all resource names we care about
    resource_names = []
    for link_name, _, _ in links:
        resource_names.append(f"{link_name}_UP")
        resource_names.append(f"{link_name}_DOWN")

    data = sim_run.get_link_utilization_over_time(resource_names)

    if data.empty:
        print("No metrics found for star links")
        return

    fig = plt.figure(figsize=(5.59, 3.5))

    time_vals = data.index

    # Needs reindexing explicitly if we want to ensure continuity, but pandas plot usually handles line gaps okay-ish
    # or we can reindex like before if strictly needed.

    for link_name, bw_bps, display_name in links:
        for direction in ["UP", "DOWN"]:
            resource_name = f"{link_name}_{direction}"
            if resource_name not in data.columns:
                continue

            s = data[resource_name]
            # Convert values (bytes/s) to utilization % of bandwidth (bits/s)
            utilization = (s * 8.0 / bw_bps) * 100.0

            label = f"{display_name} {direction}"
            linestyle = "-" if direction == "UP" else "--"

            plt.plot(time_vals, utilization, label=label, linestyle=linestyle)

    plt.xlabel("Time (s)")
    plt.ylabel("Bandwidth Utilization (%)")
    plt.legend(loc="upper right")
    plt.grid(True)
    add_git_hash(fig)
    plt.tight_layout()

    output_path = os.path.join(output_dir, "star_link_utilization.svg")
    plt.savefig(output_path)
    plt.savefig(output_path.replace(".svg", ".pgf"))
    fix_svg_latex_escapes(output_path)
    print(f"Saved plot to {output_path}")
    plt.close()


def main():
    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # infer topology path relative to net_metrics_file if possible
    # logic copied from old viz_net_metrics but applied centrally
    metrics_dir = os.path.dirname(net_metrics_file)
    topo_path = os.path.join(metrics_dir, "topology.json")

    sim_run = SimulationRun(
        mon_path=mon_metrics_file,
        net_path=net_metrics_file,
        client_path=client_metrics_file,
        topology_path=topo_path,
    )

    viz_mon_metrics(sim_run)
    viz_client_metrics(sim_run)
    viz_net_metrics(sim_run)
    viz_star_link_utilization(sim_run)


if __name__ == "__main__":
    main()
